/*
 Navicat Premium Data Transfer

 Source Server         : Mysql 7.3
 Source Server Type    : MySQL
 Source Server Version : 100316
 Source Host           : localhost:3306
 Source Schema         : iscan

 Target Server Type    : MySQL
 Target Server Version : 100316
 File Encoding         : 65001

 Date: 05/07/2021 05:07:01
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for produk
-- ----------------------------
DROP TABLE IF EXISTS `produk`;
CREATE TABLE `produk`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_toko` int NULL DEFAULT NULL,
  `kode` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `nama` varchar(128) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `harga` int NULL DEFAULT NULL,
  `ekstra` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `FK_PRODUK_TO_TOKO`(`id_toko`) USING BTREE,
  CONSTRAINT `FK_PRODUK_TO_TOKO` FOREIGN KEY (`id_toko`) REFERENCES `toko` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB AUTO_INCREMENT = 51 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of produk
-- ----------------------------
INSERT INTO `produk` VALUES (2, 8, '6575675684', 'Produk 1', 10000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:54:30\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (3, 8, '6575675685', 'Produk 2', 100000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:54:53\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"8_produk_produk2_60e22e2de092f.jpg\"}');
INSERT INTO `produk` VALUES (4, 8, '6575675686', 'Produk 3', 200000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:09\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (5, 8, '6575675687', 'Produk 4', 300000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:19\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (6, 8, '6575675688', 'Produk 5', 30000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:33\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (7, 1, '6575675684', 'Produk 1', 10000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:54:30\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (8, 1, '6575675686', 'Produk 3', 200000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:09\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (9, 1, '6575675687', 'Produk 4', 300000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:19\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (10, 1, '6575675688', 'Produk 5', 30000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:33\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (11, 2, '6575675684', 'Produk 1', 10000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:54:30\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (12, 2, '6575675686', 'Produk 3', 200000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:09\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (13, 2, '6575675687', 'Produk 4', 300000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:19\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (14, 2, '6575675688', 'Produk 5', 30000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:33\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (15, 3, '6575675684', 'Produk 1', 10000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:54:30\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (16, 3, '6575675686', 'Produk 3', 200000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:09\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (17, 3, '6575675687', 'Produk 4', 300000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:19\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (18, 3, '6575675688', 'Produk 5', 30000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:33\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (19, 4, '6575675684', 'Produk 1', 10000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:54:30\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (20, 4, '6575675686', 'Produk 3', 200000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:09\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (21, 4, '6575675687', 'Produk 4', 300000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:19\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (22, 4, '6575675688', 'Produk 5', 30000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:33\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (23, 5, '6575675684', 'Produk 1', 10000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:54:30\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (24, 5, '6575675686', 'Produk 3', 200000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:09\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (25, 5, '6575675687', 'Produk 4', 300000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:19\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (26, 5, '6575675688', 'Produk 5', 30000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:33\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (27, 6, '6575675684', 'Produk 1', 10000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:54:30\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (28, 6, '6575675686', 'Produk 3', 200000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:09\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (29, 6, '6575675687', 'Produk 4', 300000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:19\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (30, 6, '6575675688', 'Produk 5', 30000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:33\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (31, 7, '6575675684', 'Produk 1', 10000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:54:30\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (32, 7, '6575675686', 'Produk 3', 200000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:09\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (33, 7, '6575675687', 'Produk 4', 300000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:19\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (34, 7, '6575675688', 'Produk 5', 30000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:33\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (35, 9, '6575675684', 'Produk 1', 10000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:54:30\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (36, 9, '6575675686', 'Produk 3', 200000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:09\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (37, 9, '6575675687', 'Produk 4', 300000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:19\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (38, 9, '6575675688', 'Produk 5', 30000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:33\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (39, 10, '6575675684', 'Produk 1', 10000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:54:30\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (40, 10, '6575675686', 'Produk 3', 200000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:09\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (41, 10, '6575675687', 'Produk 4', 300000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:19\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (42, 10, '6575675688', 'Produk 5', 30000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:33\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (43, 11, '6575675684', 'Produk 1', 10000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:54:30\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (44, 11, '6575675686', 'Produk 3', 200000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:09\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (45, 11, '6575675687', 'Produk 4', 300000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:19\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (46, 11, '6575675688', 'Produk 5', 30000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:33\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (47, 12, '6575675684', 'Produk 1', 10000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:54:30\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (48, 12, '6575675686', 'Produk 3', 200000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:09\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (49, 12, '6575675687', 'Produk 4', 300000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:19\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');
INSERT INTO `produk` VALUES (50, 12, '6575675688', 'Produk 5', 30000, '{\"deskripsi\":\"Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque deleniti, repellendus voluptatibus at, alias modi quam nihil corporis similique placeat ex rem ad non inventore perspiciatis sed veritatis eum veniam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro commodi ut, incidunt eligendi quasi explicabo nulla reiciendis in magnam quam, perspiciatis ipsum veritatis sunt quia adipisci aliquid dolores corporis iure? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus officia exercitationem nisi, iure, suscipit ab id perspiciatis ipsum veritatis doloremque molestiae nihil assumenda harum? Repudiandae harum dicta cupiditate facere laboriosam?\",\"date_input\":\"2021-07-05 04:57:33\",\"date_last_scan\":\"\",\"scan_count\":0,\"foto\":\"default.png\"}');

SET FOREIGN_KEY_CHECKS = 1;
